-- ================================================================
-- 阶段 13 — 四类业务能力（执行计划序号 13，SQL 目录序号 14）
-- 功能清单 §5.1–§5.4 / 架构 §4.3 / §4.5
-- 依赖：07-tool-registry, 08-session-message, 09-task-worker,
--       10-capability-routing, 11-skill-management, 12-knowledge-base,
--       13-agent-runtime
-- ================================================================
--
-- 本阶段无新建表。
--
-- 四类业务能力（问答型 / 查询型 / 操作型 / 流程型）在代码层实现，
-- 数据流经已有的表结构：
--   - session（08）：记录 capability_type
--   - message（08）：记录能力执行过程消息（路由结果、引用、中间结果）
--   - task / task_step / task_log（09）：流程型任务状态化、步骤跟踪、执行日志
--   - tool（07）：四类 Tool 定义及 config（sql/http/workflow）
--   - capability / routing_rule（10）：能力目录与路由规则
--   - skill（11）：技能书与 Tool 绑定
--   - knowledge_base / kb_chunk（12）：问答型知识库检索
--
-- 增量变更：
-- 1. 为 message.content 新增统一结果结构约定（仅应用层约束，数据库 JSON 列不变）。
-- 2. 为 task 表新增索引以优化流程型任务按 capability_type 查询。
-- ================================================================

-- 优化：为 task.capability_type + status 组合查询添加索引（流程型长任务进度查询）
-- 注：idx_task_capability_type 已存在（09），此处为组合索引补充
CREATE INDEX IF NOT EXISTS `idx_task_cap_type_status_created`
    ON `task` (`capability_type`, `status`, `created_at` DESC);

-- 统一结果结构约定（应用层 JSON，非数据库约束）：
-- message.content 当 type='system' 且为能力执行结果时，遵循以下结构：
-- {
--   "capabilityType": "qa" | "query" | "action" | "workflow",
--   "data": { ... },           -- 各能力的具体输出
--   "citations": [...],        -- 问答型引用依据（可选）
--   "steps": [...],            -- 流程型步骤结果（可选）
--   "status": "success" | "failed" | "partial" | "pending_confirm"
-- }
--
-- 查询型 data 结构：
-- { "text": "...", "rows": [...], "rowCount": N, "executedSql": "..." }
--
-- 操作型 data 结构：
-- { "text": "...", "httpStatus": N, "response": {...} }
--
-- 流程型 data 结构：
-- { "text": "...", "taskId": "<task.id>" }
--
-- 问答型 data 结构：
-- { "text": "..." }
