-- 模块 06 — 连接器管理：初始化数据
--
-- 本模块无平台级初始化数据：
-- - 连接器均为各租户在运行期按需配置（含目标系统、认证凭证），不预置演示数据。
-- - 连接器菜单权限（connector）与模块权限（connector.manage）已在 03-user-rbac
--   的权限目录中预置，无需在此追加。
--
-- 保留空文件以符合 implementation-constraints §2.3（每模块至少输出 schema/seed/README）。
