-- 模块 05 — 策略引擎与规则配置 / seed
--
-- 本模块无平台级基础初始化数据：
-- - 规则（rule）为按租户的显式配置，由运营在「规则配置」页按需创建，
--   随租户接入而定，不预置演示性脏数据（实施约束 §2.2 / §2.3）。
-- - 规则命中记录（rule_hit）由运行期 Policy 评估自动写入，无需预置。
--
-- 参考：可在管理后台「规则配置」新建一条「高风险需确认」规则用于验证（验收标准 1），
-- 等价 SQL 示例（请将 <TENANT_ID> 替换为真实租户，按需执行；非交付数据）：
--
-- INSERT INTO `rule`
--   (`id`, `tenant_id`, `name`, `type`, `conditions`, `action`, `priority`, `status`, `description`, `updated_at`)
-- VALUES
--   (UUID(), '<TENANT_ID>', '高风险动作需确认', 'confirm',
--    JSON_OBJECT('match', 'any', 'riskLevels', JSON_ARRAY('high')),
--    'need_confirm', 10, 'enabled', '命中高风险等级的请求需人工确认', NOW(3));
--
-- 因此本文件保留为空，仅作占位与说明。
