-- ================================================================
-- 阶段 17 — 工作台（Phase 17 / project-sql/18-workbench）
-- 功能清单 §1.1 / 执行计划 §17
-- 依赖：04-audit-center（tool_call_audit 表）
--       07-tool-registry（tool 表）
--       09-task-worker（task 表）
--       15-approval-center（approval 表）
-- ================================================================
--
-- 本模块为纯聚合读取模块，不新增数据库表。
-- 工作台 Dashboard API 通过聚合查询以下前序表产生数据：
--
--   1. tool_call_audit（阶段 04）：工具成功率、失败率、平均响应时长
--      - 按 status 统计 success / failed 数量
--      - 按 duration_ms 计算平均响应时长
--      - 按 created_at 限定时间范围（默认近 7 天）
--
--   2. approval（阶段 14 / project-sql/15-approval-center）：高风险动作待确认列表
--      - 查询 status = 'pending' 的记录
--      - 工作台展示 Top 10 并提供跳转审批中心入口
--
--   3. task（阶段 09）：最近异常任务
--      - 查询 status IN ('failed', 'timeout') 的记录
--      - 工作台展示 Top 10 并提供跳转任务中心入口
--
-- 以上查询均按租户隔离（tenantId），非超管仅可见其绑定租户数据。
--
-- 无新增表、无新增索引、无结构变更。
-- ================================================================
